---
title: "EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data_join}
library(ezids)
movies <- read.csv('movies.csv', header=TRUE)
str(movies)
# our dataset has 85855 observations of  22 variables.

drop <- c('budget','usa_gross_income','worlwide_gross_income','metascore','reviews_from_users',
          'reviews_from_critics','production_company','description','writer')
movies <- movies[,!names(movies) %in% drop]
movies <- movies[!(movies$country == "") & !(movies$language == "") & !(movies$director == "") & !(movies$actors == ""),]
# we cleaned the data: drop 'budget','usa_gross_income','worlwide_gross_income','metascore','reviews_from_users',
#'reviews_from_critics','production_company','description','writer' because they are not related.we dropped “NA” #values from the dataset to simplify our analysis.


ratings <- read.csv('ratings.csv', header=TRUE)
drop <- c('allgenders_0age_avg_vote', 'allgenders_0age_votes', 'males_0age_avg_vote', 'males_0age_votes',
          'females_0age_avg_vote', 'females_0age_votes', 'us_voters_rating', 'us_voters_votes', 
          'non_us_voters_rating', 'non_us_voters_votes')
ratings <- ratings[,!names(ratings) %in% drop]
ratings <- na.omit(ratings)
movie_ratings <- merge(movies, ratings, by="imdb_title_id" )

```


```{r Q1}
library(dplyr)
library(reshape)
movie_genre <- movie_ratings[,c("genre", "avg_vote")]
movie_genre <- movie_genre %>%
  mutate(
      Romance = grepl('Romance', genre),
      Biography = grepl('Biography', genre),
      Drama = grepl('Drama', genre),
      Adventure = grepl('Adventure', genre),
      History = grepl('History', genre),
      Crime = grepl('Crime', genre),
      Western = grepl('Western', genre),
      Fantasy = grepl('Fantasy', genre),
      Comedy = grepl('Comedy', genre),
      Horror = grepl('Horror', genre),
      Family = grepl('Family', genre),
      Action = grepl('Action', genre),
      Mystery = grepl('Mystery', genre),
      Sci_Fi = grepl('Sci-Fi', genre),
      Animation = grepl('Animation', genre),
      Thriller = grepl('Thriller', genre),
      Musical = grepl('Musical', genre),
      Music = grepl('Music', genre),
      War = grepl('War', genre),
      Film_Noir = grepl('Film-Noir', genre),
      Sport = grepl('Sport', genre),
      Adult = grepl('Adult', genre),
      Documentary = grepl('Documentary', genre),
      Reality_TV = grepl('Reality-TV', genre),
      News = grepl('News', genre)
  )
melt(movie_genre,id.vars = "genre", measure.vars = c("Romance",'Biography'), value.name = "avg_vote"
)
```


```{r Q2}

hist(movies$avg_vote)
library(ggplot2)
movie_director <- movie_ratings[,c("director", "avg_vote")]
movie_director

director_gourp <- aggregate(movie_director$avg_vote, by = list(director = movie_director$director),FUN=mean)
director_num <- movie_director %>% count(director,sort = TRUE)
director_vote <- merge(director_gourp,director_num,by='director')
director_vote <- director_vote[order(-director_vote$n),]
colnames(director_vote) <- c('director','rating','movie_numbers') 
director_vote

director_vote_40 <- subset(director_vote,movie_numbers>39)
director_vote_40$rating <- as.numeric(director_vote_40$rating)


ggplot(director_vote_40,aes(x=reorder(director,rating),y=rating))+
     geom_bar(stat='identity',fill='#f68060',alpha=.6, width=.4)+
     labs(title="Rating plot for directors(Moive numbers more than 40)")+
     coord_flip()+
     xlab('directors')+
     theme_bw()

```
```{r decription of the data}
library(dplyr)
library(ggplot2)
# average vote distribution
summary(movies$avg_vote)
movies<-movies[!movies$year=='TV Movie 2019',]
hist(movies$avg_vote)
# A brief overview of the dataset: the minimum vote is 1.000,while the maximum vote is 9.900.
# the mean of the vote is 5.902, the median is 6.100.


# movies year-numbers distribution
years_numbers <- movies[,c('imdb_title_id', 'year')]
years_num <- years_numbers %>% count(year,sort = TRUE)
colnames(years_num)<-c('Year','Movie_numbers')
df1 <-arrange(years_num, -Movie_numbers)
head(df1)
tail(df1)


ggplot(years_num,aes(x=Year,y=Movie_numbers))+geom_col(stat='identity',fill='#f68060',alpha=.6, width=1)+labs(title=('year and Movie_numbers'))+coord_flip()+ylab('Year') + scale_x_discrete(guide = guide_axis(n.dodge=3))



# movies year-rating distribution
years_rating <- aggregate(movies$avg_vote, by = list(director = movies$year),FUN=mean)
colnames(years_rating) <- c('Year','Rating')
df2 <-arrange(years_rating, -Rating)
head(df2)
tail(df2)


ggplot(data=years_rating,aes(x=Year,y=Rating)) +geom_col(width=1,fill='lightblue')+coord_flip()+xlab('Year')+labs(title=('years and Rating'))+ scale_x_discrete(guide = guide_axis(n.dodge=3))
```

```{r decription of the data}
# movies vote distribution
years_vote <- aggregate(movies$votes, by = list(director = movies$year),FUN=sum)
colnames(years_vote) <- c('Year','Votes')
df3 <-arrange(years_vote, -Votes)
head(df3)
tail(df3)


ggplot(data=years_vote,aes(x=Year,y=Votes)) +geom_col(fill='purple4',alpha=1, width=1)+xlab('Year')+ylab('Votes')+coord_flip()+labs(title=('Year and votes'))+ scale_x_discrete(guide = guide_axis(n.dodge=3))

# movies duration-year distribution
years_duration <- aggregate(movies$duration, by = list(director = movies$year),FUN=mean)
colnames(years_duration) <- c('Year','Duration')
df4 <-arrange(years_duration, -Duration)
head(df4)
tail(df4)

ggplot(data=years_duration,aes(x=Year,y=Duration)) +geom_col(fill='purple4',alpha=1, width=1)+xlab('Year')+ylab('Duration')+coord_flip()+labs(title=('Year and Duration'))+ scale_x_discrete(guide = guide_axis(n.dodge=3))
```

```{r decription of the data}
# movies duration-rating distribution
duration <-outlierKD2(movies,movies$duration)
outliers <- boxplot(movies$duration,plot=FALSE)$out
movies1 <- movies[-which(movies$duration %in% outliers),]
summary(movies$duration)
duration_rating <- movies1[,c('duration','avg_vote')]
colnames(duration_rating)<-c("duration","rating")
df5 <-arrange(duration_rating, -rating)
head(df5)
tail(df5)


ggplot(data=duration_rating,,mapping=aes(x=duration,y=rating)) +geom_col(fill='purple4',alpha=.6)+labs(title=('duration and rating'))


theme_set(theme_bw())

duration_grouped <- duration_rating %>%
  group_by(duration) %>%
    summarize(
      mean_vote = mean(rating),
      n=n()
    )

# duration_grouped <- duration_grouped[order(duration_grouped$mean_vote), ]
# duration_grouped$duration <- factor(duration_grouped$duration, levels = duration_grouped$duration)

ggplot( duration_grouped, aes(fill=mean_vote, y=mean_vote, x=duration)) +
    geom_bar(width=.8, stat="identity") +
        coord_flip() +
            labs(title="Ordered Bar Chart",
                subtitle="Mean Rating across film genres", 
                caption="duration: Rating")




#correlation 
cor.test(movies$avg_vote,as.numeric(movies$year))
cor.test(movies$avg_vote,as.numeric(movies$duration))
ggplot(movies,aes(x=duration,y=avg_vote))+ ylab('Rating')+geom_point()

```