---
title: "EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data_join}
movies <- read.csv('movies.csv', header=TRUE)
drop <- c('budget','usa_gross_income','worlwide_gross_income','metascore','reviews_from_users',
          'reviews_from_critics','production_company','description','writer')
movies <- movies[,!names(movies) %in% drop]
movies <- movies[!(movies$country == "") & !(movies$language == "") & !(movies$director == "") & !(movies$actors == ""),]
ratings <- read.csv('ratings.csv', header=TRUE)
drop <- c('allgenders_0age_avg_vote', 'allgenders_0age_votes', 'males_0age_avg_vote', 'males_0age_votes',
          'females_0age_avg_vote', 'females_0age_votes', 'us_voters_rating', 'us_voters_votes', 
          'non_us_voters_rating', 'non_us_voters_votes')
ratings <- ratings[,!names(ratings) %in% drop]
ratings <- na.omit(ratings)
movie_ratings <- merge(movies, ratings, by="imdb_title_id" )

```


```{r Q1}
movie_genre <- movie_ratings[,c("genre", "avg_vote")]
movie_genre <- movie_genre %>%
  mutate(
      Romance = grepl('Romance', genre),
      Biography = grepl('Biography', genre),
      Drama = grepl('Drama', genre),
      Adventure = grepl('Adventure', genre),
      History = grepl('History', genre),
      Crime = grepl('Crime', genre),
      Western = grepl('Western', genre),
      Fantasy = grepl('Fantasy', genre),
      Comedy = grepl('Comedy', genre),
      Horror = grepl('Horror', genre),
      Family = grepl('Family', genre),
      Action = grepl('Action', genre),
      Mystery = grepl('Mystery', genre),
      Sci_Fi = grepl('Sci-Fi', genre),
      Animation = grepl('Animation', genre),
      Thriller = grepl('Thriller', genre),
      Musical = grepl('Musical', genre),
      Music = grepl('Music', genre),
      War = grepl('War', genre),
      Film_Noir = grepl('Film-Noir', genre),
      Sport = grepl('Sport', genre),
      Adult = grepl('Adult', genre),
      Documentary = grepl('Documentary', genre),
      Reality_TV = grepl('Reality-TV', genre),
      News = grepl('News', genre)
  )
library(tidyr)
library(stringr)
library(plyr)
movie_genre <- movie_genre %>%
  separate(genre,c("c1",'c2','c3'),sep =c(',',' '))
movie_genre
df1<-data.frame(movie_genre$c1,movie_genre$avg_vote)
df2<-data.frame(movie_genre$c2,movie_genre$avg_vote)
df3<-data.frame(movie_genre$c3,movie_genre$avg_vote)
df1%>%drop_na(movie_genre.c1)
df2%>%drop_na(movie_genre.c2)
df3%>%drop_na(movie_genre.c3)
colnames(df1)<-c("movie_genre","avg_vote")
colnames(df2)<-c("movie_genre","avg_vote")
colnames(df3)<-c("movie_genre","avg_vote")
#inbind_rows(df1, df2, df3)
dfs<-rbind.fill(df1,df2,df3)
dfs
#drops <- c("movie_genre.c2","movie_genre.c3")
#dfs[ , !(names(dfs) %in% drops)]
```